### ISSUE TITLE
Potential security issue with baseURI

### ISSUE THREAD

**Issue by eguajardo** [HashLips/hashlips_nft_contract#32]
I found a potential issue, everything in the blockchain is public from outside even if the variables are set to private. The token constructor allows to set the baseURI before the tokens are revealed, in this case anyone could decode the contract storage and know in advance the tokens they will get before minting. Ideally the baseURI should not be allowed to be set until the tokens are revealed.

**Comment by liarco** [comment]
Hi @eguajardo, you are right, this is a well-known thing in the space. That's why we came up with tools like the https://github.com/hashlips-lab/safe-nft-metadata-provider to help people protecting their collections.

Our brand new ERC721 contract is also encouraging a different workflow where that value is never exposed until the very end: https://github.com/hashlips-lab/nft-erc721-collection

I hope this helps, but thank you for your feedback.
